GET http://localhost:8000/cities
Content-Type: application/json

{
    "name": "Berlin",
    "population": "99999",
    "federalState": "Berlin"
}

###

GET http://localhost:8000/cities/5dfa65e33c04771bf730de4f

###

POST http://localhost:8000/cities
Content-Type: application/json

{
    "name": "Berlin",
    "population": "99999",
    "federalState": "Berlin"
}

###

DELETE http://localhost:8000/cities/5dfa65e23c04771bf730de4e

###

PATCH http://localhost:8000/cities/5dfa65e33c04771bf730de4f
Content-Type: application/json

{
    "population": "Hamburg"
}