GET http://localhost:8000/cities

###

GET http://localhost:8000/cities/5dfa65e13c04771bf730de4df

###

POST http://localhost:8000/cities
Content-Type: application/json

{
    "name": "Berlin",
    "population": "99999",
    "federalState": "Berlin"
}